baseURL: https://aciklab.org
languageCode: tr-tr
title: HAVELSAN Açıklab
theme: aciklab-hugo
googleAnalytics:
disableKinds:
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
menu:
  main:
  - identifier: home
    name: "Ana Sayfa"
    url: "/"
    weight: 1
  footer:
  - identifier: diger
    name: "/images/aciklab_white.png"
  - parent: diger
    name: "Dokümanlar"
    url: "https://docs.liman.dev"
  - parent: diger
    name: "DEV.to Blog"
    url: "https://dev.to/aciklab"

permalinks:
  posts: /duyurular/:title/

paginate: 4

params:
  openGraph: true
  description: HAVELSAN Açıklab Açık Kaynaklı Yazılım Geliştirme
  navbarlogo:
    main:
      image: aciklab-new-logo.png
    sub:
      image: sub.svg
  banner:
    text: Açık kaynak ürünleri ile ilgili bilgi için iletişime geçin!
    button_text: İletişime geçin
    button_link: "/iletisim"
  hero:
    - title: HAVELSAN Açıklab
      subtitle: Açık kaynak projeler geliştirerek; Türkiye başta olmak üzere tüm dünyada kullanılan açık kaynak güvenilir, inovatif ürünler sunmak, bu anlamda Türkiye’nin yazılım dışa bağımlılığını azaltmak, Türkiye’de açık kaynak kullanımını artırmak, dünyaca bilinir bir açık kaynak yazılım şirketi olmayı hedeflemektedir.
      buttons:
        - text: Şimdi Bilgi Alın
          link: "iletisim"
      image: aciklab_slide_1

  section_about: 
    video_link: "https://www.youtu.be/yZyScWN2IbQ"
    thumbnail: video-holder.png
    title: Liman Yönetimi
    text: "PHP dili kullanılarak Laravel Frameworkü ile geliştirilmiştir. Liman MYS özellikleri eklenti olarak isimlendirdiğimiz paket yönetim sistemi baz alınarak tasarlandı.<br />
    Liman MYS ile kullanımda olan dizinlerin (Samba, Aktif Dizin) entegrasyonu hizmetler kesintiye uğramadan sağlanmaktadır. <br />
    Liman MYS'nin bileşenleri: Liman, Kaptan, Tayfa olarak üçe ayrılmıştır. Bu bileşenler, Liman MYS'nin kararlı ve güvenli olarak çalışmasını sağlar. <br />
    Liman Mimari olarak yönetilecek uç birimlerde “C/ C++  ” programlama dili ile ile geliştirilmiş “Tayfa ” adında minimal kaynak tüketen ajanlarımız bulunmaktadır."
  footer:
    logo: footer-logo.png
    socialmedia:
      - link: https://github.com/aciklab
        icon: "feather-github"
      - link: https://www.aciklab.org/
        icon: "feather-globe"
      - link: mailto:aciklab@havelsan.com.tr
        icon: "feather-mail"
module:
  imports:
    path: "github.com/gohugoio/hugo-mod-bootstrap-scss-v4"
