baseURL: https://aciklab.org
languageCode: tr-tr
title: HAVELSAN Açıklab
theme: aciklab-hugo
googleAnalytics:
disableKinds:
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
menu:
  main:
  - identifier: home
    name: "Ana Sayfa"
    url: "/"
    weight: 1
  - identifier: about
    name: "Keşfedin"
    url: ""
    weight: 2
  - identifier: policies
    name: "Politikalar"
    parent: "about"
    url: "/#policies"
    weight: 3
  - identifier: comparison
    name: "Karşılaştırma"
    parent: "about"
    url: "/#comparison"
    weight: 2
  footer:
  - identifier: diger
    name: "/images/aciklab_white.png"
  - identifier: home
    parent: diger
    name: "Ana Sayfa"
    url: "/"

permalinks:
  posts: /haberler/:title/

params:
  openGraph: true
  description: HAVELSAN Liman Merkezi Yönetim Sistemi
  navbarlogo:
    main:
      image: aciklab_white.png
    sub:
      image: sub.svg
  banner:
    text: Açık kaynak ürünleri ile ilgili bilgi için iletişime geçin!
    button_text: Deneme Sürümü
    button_link: "/iletisim"
  hero:
    - title: Eğitimler
      subtitle: Açık kaynak kodlu sistemler hakkında bilgi birikiminizi arttırın ve hakim olun.
      logos:
        - image: "aciklab.png"
      buttons:
        - text: Şimdi Bilgi Alın
          link: "neden-liman-mys"
      image: slide
    - title: Hizmetler
      subtitle: Pardus ve açık kaynaklı yazılımlar üzerine olan hizmetlerimizi inceleyin.
      logos:
        - image: "aciklab.png"
      buttons:
        - text: Hizmetlerimiz
          link: https://github.com/limanmys
      image: liman-gorsel
  section_about: 
    video_link: "https://www.youtu.be/yZyScWN2IbQ"
    thumbnail: video-holder.png
    title: Liman Yönetimi
    text: "PHP dili kullanılarak Laravel Frameworkü ile geliştirilmiştir. Liman MYS özellikleri eklenti olarak isimlendirdiğimiz paket yönetim sistemi baz alınarak tasarlandı.<br />
    Liman MYS ile kullanımda olan dizinlerin (Samba, Aktif Dizin) entegrasyonu hizmetler kesintiye uğramadan sağlanmaktadır. <br />
    Liman MYS'nin bileşenleri: Liman, Kaptan, Tayfa olarak üçe ayrılmıştır. Bu bileşenler, Liman MYS'nin kararlı ve güvenli olarak çalışmasını sağlar. <br />
    Liman Mimari olarak yönetilecek uç birimlerde “C/ C++  ” programlama dili ile ile geliştirilmiş “Tayfa ” adında minimal kaynak tüketen ajanlarımız bulunmaktadır."
  footer:
    logo: footer-logo.png
    socialmedia:
      - link: https://github.com/aciklab
        icon: "fa fa-github"
      - link: https://www.aciklab.com/
        icon: "fa fa-globe"
      - link: mailto:aciklab@havelsan.com.tr
        icon: "fa fa-envelope"
module:
  imports:
    path: "github.com/gohugoio/hugo-mod-bootstrap-scss-v4"
