baseURL: https://aciklab.org
languageCode: tr-tr
title: HAVELSAN Açıklab
theme: aciklab-hugo
googleAnalytics:
disableKinds:
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
menu:
  main:
  - identifier: home
    name: "Ana Sayfa"
    url: "/"
    weight: 1
  - identifier: news
    name: "Liman MYS"
    url: "https://liman.havelsan.com.tr/"
    weight: 1
  footer:
  - identifier: diger
    name: "/images/aciklab_white.png"

permalinks:
  posts: /duyurular/:title/

paginate: 4

params:
  openGraph: true
  description: HAVELSAN Açıklab Açık Kaynaklı Yazılım Geliştirme
  navbarlogo:
    main:
      image: aciklab_pardus2.png
    sub:
      image: sub.svg
  banner:
    text: Açık kaynak ürünleri ile ilgili bilgi için iletişime geçin!
    button_text: İletişime geçin
    button_link: "/iletisim"
  hero:
    - title: Açık Kaynak Teknoloji Kampı
      subtitle: HAVELSAN olarak açık kaynak kodlu teknolojiler alanında kamu kurumları, askeri kurumlar ve özel sektör alt yapılarında bulunan kurumsal lisanslı ürünlerin açık kaynak teknolojileri alanında dönüşümünü hedeflemektedir. HAVELSAN Açık Kaynak Teknoloji Kampı ile Türkiye’nin dijital dönüşümünde açık kaynak teknlojileri alanında görev alacak gençlerin kariyer gelişimine katkı sunmayı hedefliyoruz.
      buttons:
        - text: Detaylı Bilgi
          link: /duyurular/a%C3%A7%C4%B1k-kaynak-teknoloji-kamp%C4%B1-ba%C5%9Fvurular%C4%B1-ba%C5%9Flad%C4%B1/
        - text: Hemen Başvur!
          link: https://vizyonergenc.com/ilan/havelsan/1505-acik-kaynak-teknoloji-kampi
      image: aciklab_slide_1
    - title: HAVELSAN Açıklab
      subtitle: Açık kaynak projeler geliştirerek; Türkiye başta olmak üzere tüm dünyada kullanılan açık kaynak güvenilir, inovatif ürünler sunmak, bu anlamda Türkiye’nin yazılım dışa bağımlılığını azaltmak, Türkiye’de açık kaynak kullanımını artırmak, dünyaca bilinir bir açık kaynak yazılım şirketi olmayı hedeflemektedir.
      buttons:
        - text: Şimdi Bilgi Alın
          link: "egitimler"
      image: aciklab_slide_1
    - title: Merkezi Yönetim Sistemi
      subtitle: BT süreçlerinizde bulunan bütün bileşenleri uzaktan, kararlı, güvenli ve genişletilebilir yöntemler ile merkezi olarak yönetmenizi sağlar.<br/><br/>Açık kaynak göç projelerinde Linux çekirdeğine sahip işletim sistemlerini ve diğer platformları Liman MYS ile yönetebilirsiniz.
      buttons:
        - text: Neden Liman MYS?
          link: "https://liman.havelsan.com.tr/neden-liman-mys/"
        - text: Demo Talebi
          link: "https://liman.havelsan.com.tr/iletisim/"
      image: liman-screen  

  section_about: 
    video_link: "https://www.youtu.be/yZyScWN2IbQ"
    thumbnail: video-holder.png
    title: Liman Yönetimi
    text: "PHP dili kullanılarak Laravel Frameworkü ile geliştirilmiştir. Liman MYS özellikleri eklenti olarak isimlendirdiğimiz paket yönetim sistemi baz alınarak tasarlandı.<br />
    Liman MYS ile kullanımda olan dizinlerin (Samba, Aktif Dizin) entegrasyonu hizmetler kesintiye uğramadan sağlanmaktadır. <br />
    Liman MYS'nin bileşenleri: Liman, Kaptan, Tayfa olarak üçe ayrılmıştır. Bu bileşenler, Liman MYS'nin kararlı ve güvenli olarak çalışmasını sağlar. <br />
    Liman Mimari olarak yönetilecek uç birimlerde “C/ C++  ” programlama dili ile ile geliştirilmiş “Tayfa ” adında minimal kaynak tüketen ajanlarımız bulunmaktadır."
  footer:
    logo: footer-logo.png
    socialmedia:
      - link: https://github.com/aciklab
        icon: "fa fa-github"
      - link: https://www.aciklab.org/
        icon: "fa fa-globe"
      - link: mailto:aciklab@havelsan.com.tr
        icon: "fa fa-envelope"
module:
  imports:
    path: "github.com/gohugoio/hugo-mod-bootstrap-scss-v4"
